version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env   # <-- esto carga tu .env local
    volumes:
      - ./storage:/app/storage
      - ./uploads:/app/uploads
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
